version: "3"

services:
    web:
        container_name: api-culqui
        restart: always
        build: .
        ports:
            - "3000:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: mongo-culqui
        image: mongo
        ports:
            - "27018:27017"
        logging:
            driver: none